### ISSUE TITLE
Adding CRX..

### ISSUE THREAD

**Issue by bcookatpcsd** [ungoogled-software/ungoogled-chromium-wiki#14]
Hey there.. 

btw, I run arch.. 

and Plasma.. 

I'm installing ungoogled-chromium from chaotic-aur.

I needed to make chromium my default browser before I could get the crx to install.. (lastpass fwiw)

My 0.02

**Comment by Eloston** [comment]
Sorry I don't understand your problem. Can you clarify?

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
