### ISSUE TITLE
Minor updates for widevine-cdm faq

### ISSUE THREAD

**Issue by Pandalism** [ungoogled-software/ungoogled-chromium-wiki#16]
Hi, as seen in the [ungoogled-chromium/issues/1120](https://github.com/Eloston/ungoogled-chromium/issues/1120), the file containing the versions is pointing to the defunct [current.txt](https://dl.google.com/widevine-cdm/current.txt).
The [versions.txt](https://dl.google.com/widevine-cdm/versions.txt) seems to be up to date.

Additionally, for users of the portable installation, its not entirely crystal clear where the folder goes, so i propose adding this line:

> Create a catalogue under `User Data` for your Chromium installation and call it `WidevineCdm`. For portable installations, place in the root folder directly, like so: `PortableChromium\WidevineCdm`

Happy to make these changes myself, if I am allowed

**Comment by EPIVISION** [comment]
Additionally, please fix a _breaking typo_ [at](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#windows) that fucked me over for like 2 hours:

> 4. Inside that create another folder called `_plaform_specific`.

# called `_platform_specific`. t !!11!!1! 🤪
---
Also for all the folks with a **.zip-"installation"**:

> 3. Create a catalogue under `User Data` for your Chromium installation and call it `WidevineCdm`

actually: Create a directory under your Chromium installation (next to the `chrome.exe`) and call it `WidevineCdm`
```
Directory of <wherever you unzipped>\ungoogled-chromium\87.0.4280.141-1

06.02.2021  23:44    <DIR>          .
06.02.2021  23:44    <DIR>          ..
09.01.2021  14:14               226 87.0.4280.141.manifest
10.01.2021  14:08       143.196.160 chrome.dll
10.01.2021  14:09         1.961.472 chrome.exe
...
07.02.2021  00:18    <DIR>          WidevineCdm
```

**Comment by EPIVISION** [comment]
https://github.com/Eloston/ungoogled-chromium/issues/1120
