### ISSUE TITLE
Widevine CDM installation on Windows has changed

### ISSUE THREAD

**Issue by ilfarpro** [ungoogled-software/ungoogled-chromium-wiki#17]
Part "How do I install Widevine CDM?" (on Windows) is not working now. I've figured out that Widevine works only if you put it on this directory C:\Users\{username}\AppData\Local\Chromium\Application\{chrome_version}\
So, this is the path you should use to place your WidevineCdm folder that you've made by wiki.

**Comment by Mysticodex** [comment]
Tried this, didn't work. 

Widevine's manifest contained the following, let me know if it's matching yours?

{
    "arch": "x64",
    "description": "Widevine Content Decryption Module",
    "manifest_version": 2,
    "name": "WidevineCdm",
    "os": "win",
    "version": "1.4.9.1088",
    "x-cdm-codecs": "vp8,vp9.0,avc1",
    "x-cdm-host-versions": "9",
    "x-cdm-interface-versions": "9",
    "x-cdm-module-versions": "4",
    "x-cdm-persistent-license-support": true
}

**Comment by ilfarpro** [comment]
My manifest.json from C:\Users\{username}\AppData\Local\Chromium\Application\87.0.4280.141\WidevineCdm

{
  "manifest_version": 2,
  "update_url": "https://clients2.google.com/service/update2/crx",
  "name": "WidevineCdm",
  "description": "Widevine Content Decryption Module",
  "version": "4.10.1679.0",
  "minimum_chrome_version": "68.0.3430.0",
  "x-cdm-module-versions": "4",
  "x-cdm-interface-versions": "10",
  "x-cdm-host-versions": "10",
  "x-cdm-codecs": "vp8,vp09,avc1,av01",
  "x-cdm-persistent-license-support": true,
  "x-cdm-supported-encryption-schemes": ["cenc","cbcs"],
  "icons": {
    "16": "imgs/icon-128x128.png",
    "128": "imgs/icon-128x128.png"
  },
  "platforms": [
    {
      "os": "win",
      "arch": "x86",
      "sub_package_path": "_platform_specific/win_x86/"
    },
    {
      "os": "win",
      "arch": "x64",
      "sub_package_path": "_platform_specific/win_x64/"
    },
    {
      "os": "mac",
      "arch": "x64",
      "sub_package_path": "_platform_specific/mac_x64/"
    }
  ]
}

And this is manifest.json from C:\Users\{username}\AppData\Local\Chromium\User Data\WidevineCdm

{
    "arch": "x64",
    "description": "Widevine Content Decryption Module",
    "manifest_version": 2,
    "name": "WidevineCdm",
    "os": "win",
    "version": "1.4.9.1088",
    "x-cdm-codecs": "vp8,vp9.0,avc1",
    "x-cdm-host-versions": "9",
    "x-cdm-interface-versions": "9",
    "x-cdm-module-versions": "4",
    "x-cdm-persistent-license-support": true
}

I don't know why but in my case Widevine work only if I put it on C:\Users{username}\AppData\Local\Chromium\Application{chrome_version} after Ungoogled Chromium installation.
