### ISSUE TITLE
Dictionary installation instructions for Windows are invalid/outdated

### ISSUE THREAD

**Issue by tomasz1986** [ungoogled-software/ungoogled-chromium-wiki#18]
The instructions at https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#how-do-i-fix-the-spell-checker suggest using 7-Zip to "unpack" the base64 encoded files. However, in reality 7-Zip is unable to open such files (at least when using the current stable version of 7-Zip 19.00).

The proper way to decode a base64 file in Windows is to use the built-in `certutil.exe` utility (see https://stackoverflow.com/questions/16945780/decoding-base64-in-batch), which works more or less similarly to the `base64` tool used in Linux, e.g.

```
certutil.exe -decode en-US-9-0.bdic.txt en-US-9-0.bdic
```

**Comment by networkException** [comment]
Do you know where the decoded output would go? `%LOCALAPPDATA%\Chromium\User Data\Dictionaries` doesn't seem to exist

**Comment by tomasz1986** [comment]
The correct path seems to be `%LOCALAPPDATA%\Chromium\Application\Dictionaries`. The dictionaries are then shared between different profiles.
