### ISSUE TITLE
u2f extension link is dead

### ISSUE THREAD

**Issue by wc2FiCLd** [ungoogled-software/ungoogled-chromium-wiki#22]
In the FAQ, you said that it's required to use "this extension" but that link is dead, goes to 404 google
There is no name for the extension needed. Do you have it anywhere, is there a new version or something?

"How to get FIDO U2F security keys to work in Google sign in?"
Google sign in uses a specific extension to access the security key’s information. You’ll need to install [this extension](https://chrome.google.com/webstore/detail/gnubbyd/beknehfpfkghjoafdifaflglpjkojoco) to make this function. After installation you might need to restart your computer to make it work.

**Comment by networkException** [comment]
That extension never worked for me personally so the section should probably be removed entirely now.

As Chromium is deprecating non WebAuthn hardware key apis anyways it shouldn't take too long until Google updates their login as well

**Comment by wc2FiCLd** [comment]
Until they do it would be nice to have a little update in that FAQ so that people will know they can't use a yubikey.
