### ISSUE TITLE
add Disable JIT info to Wiki

### ISSUE THREAD

**Issue by joey04** [ungoogled-software/ungoogled-chromium-wiki#24]
Since [this wiki page](https://ungoogled-software.github.io/ungoogled-chromium-wiki/user-resources) has info on Disabling WebAssembly, it would be suitable to also include info on Disabling JIT, which is easy to do [with a launch flag](https://github.com/ungoogled-software/ungoogled-chromium/issues/1583#issuecomment-892600508).

The [potential security benefits](https://microsoftedge.github.io/edgevr/posts/Super-Duper-Secure-Mode/) may be of interest to some users, particularly since Edge now has this feature.

**Comment by PF4Public** [comment]
Would you like to do a PR?

**Comment by joey04** [comment]
No, I'd have to set up git to do that.

But here's how I'd write it (if you want to add it):

> The [JIT](https://en.wikipedia.org/wiki/Just-in-time_compilation) optimization of JavaScript is a [known attack vector](https://microsoftedge.github.io/edgevr/posts/Super-Duper-Secure-Mode/). It can be disabled with the launch flag `--js-flags='--jitless'`.
> 
> Note that disabling JIT can make websites slower, especially web apps like Google Maps. And it also disables WebAssembly.

**Comment by PF4Public** [comment]
> No, I'd have to set up git to do that.

You don't have to. Simple file editor is implemented in GitHub web.
