### ISSUE TITLE
[windows] info how to set env to use VS from non-standart directory

### ISSUE THREAD

**Issue by r4sas** [ungoogled-software/ungoogled-chromium-wiki#5]
As known, chromium build scripts prefer installation of VS in default directory, like `C:\Program Files\Microsoft Visual Studio\17\Community`.

But sometimes it is not possible to install VS to default path, so to bypass that restriction and define path to MVS installation you can use `vs2017_install` env variable.

Before running `build.py` in command line, execute command to add to env that variable:
```cmd
set vs2017_install=X:\path\to\MVS17\edition
```

That will help avoid such error:
>Exception: Visual Studio Version 2017 (from GYP_MSVS_VERSION) not found.
>ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.

**Comment by Eloston** [comment]
This is very specific to building for Windows, so I think this should be documented in `ungoogled-chromium-windows`.

**Comment by Eloston** [comment]
If you'd like, you can make a PR against the README in ungoogled-chromium-windows, otherwise you can just post a new issue for now. Thanks!
